export const WORD_LIST = [
  'apple', 'bridge', 'canyon', 'dance', 'earth', 'forest', 'glass', 'house',
  'island', 'jungle', 'knife', 'lemon', 'mirror', 'night', 'ocean', 'piano',
  'queen', 'river', 'stone', 'tiger', 'umbrella', 'valley', 'water', 'xenon',
  'yellow', 'zebra', 'anchor', 'basket', 'candle', 'dragon', 'eagle', 'flame',
  'garden', 'hammer', 'insect', 'jacket', 'kernel', 'lantern', 'marble', 'needle',
  'orange', 'pencil', 'quartz', 'rabbit', 'shadow', 'temple', 'unique', 'violet',
  'wallet', 'x-ray', 'yacht', 'zipper', 'alarm', 'blaze', 'cactus', 'desert',
  'empire', 'factor', 'galaxy', 'harbor', 'impact', 'jasper', 'kayak', 'legend',
  'mango', 'nebula', 'oyster', 'palace', 'quarry', 'rocket', 'sunset', 'tundra',
  'update', 'vacuum', 'window', 'xylophone', 'yogurt', 'zenith', 'atlas', 'bacon',
  'cedar', 'delta', 'eleven', 'fable', 'gravel', 'herald', 'ivory', 'jewel',
  'kitten', 'lotus', 'magnet', 'nickel', 'otter', 'pebble', 'quill', 'ranch',
  'silver', 'tablet', 'urchin', 'vapor', 'winter', 'xerox', 'yonder', 'zeal',
  'amber', 'birch', 'coral', 'dagger', 'ember', 'ferry', 'grotto', 'holly',
  'ingot', 'joker', 'kiwi', 'lava', 'mortar', 'neon', 'opal', 'prism',
  'quasar', 'raven', 'sphinx', 'topaz', 'ultra', 'vortex', 'walrus', 'xylem',
  'yam', 'zone', 'abyss', 'bluff', 'cliff', 'drift', 'epoch', 'fjord',
  'glyph', 'haze', 'igloo', 'jumble', 'knave', 'loft', 'manor', 'nymph',
  'orbit', 'plume', 'quest', 'realm', 'surge', 'torch', 'ulcer', 'verge',
  'whirl', 'xeric', 'yearn', 'zephyr', 'acorn', 'bloom', 'charm', 'dune',
  'elbow', 'frost', 'gleam', 'hound', 'image', 'joust', 'kindle', 'latch',
  'moose', 'notch', 'onset', 'plank', 'quirk', 'ridge', 'stork', 'thorn',
  'untie', 'visor', 'wheat', 'yacht', 'yoke', 'azure', 'brisk', 'crisp',
  'dwarf', 'elixir', 'frond', 'glide', 'hatch', 'infer', 'joust', 'knoll',
  'lyric', 'mirth', 'noble', 'olive', 'plaid', 'quake', 'resin', 'swamp',
]
